CUDA_VISIBLE_DEVICES=0 python ./softgym/test.py \
  --env_name RopeConfiguration \
  --task rope-configuration \
  --shape S \
  --step 1 \
  --agent aff_critic \
  --num_demos 7900 \
  --out_logits 1 \
  --exp_name 1022-05-S-tryseven-expert-exp \
  --process_num 1 \
  --num_test 20 \
  --critic_depth 1 \
  --expert_pick \
  --load_critic_dir checkpoints/rope-configuration-Aff_Critic-7900-1021-16-tryseven-S-no_perturb-step-1/critic-ckpt-90000.h5 \
  --load_critic_mean_std_dir checkpoints/rope-configuration-Aff_Critic-7900-1021-16-tryseven-S-no_perturb-step-1 \
  --exp \
  --image_size 160 \
  --save_video_dir './test_video/' \
  --headless 1
