CUDA_VISIBLE_DEVICES=6 python ./softgym/train.py \
  --env_name ClothFlatten \
  --task cloth-flatten \
  --agent aff_critic \
  --num_demos 7000 \
  --extra_num_demos 6000 \
  --num_iters 300000 \
  --out_logits 1 \
  --step 2 \
  --demo_times 10 \
  --extra_demo_times 5 \
  --exp_name 0917-05-tryseven-step2-many_model-mix \
  --suffix tryseven-step2 \
  --extra_suffix tryseven-step1 \
  --max_load 3000 \
  --batch 3 \
  --learning_rate 2e-4 \
  --model critic \
  --load_aff_dir checkpoints/cloth-flatten-Aff_Critic-7500-0909-02-tryseven-aff-not_on_cloth_zero-step-1/attention-ckpt-300000.h5 \
  --load_critic_dir checkpoints/cloth-flatten-Aff_Critic-7500-0907-02-tryseven-not_on_cloth_zero-step-1/critic-ckpt-300000.h5

