CUDA_VISIBLE_DEVICES=5 python ./softgym/train.py \
  --env_name RopeConfiguration \
  --task rope-configuration \
  --agent aff_critic \
  --suffix tryseven-step2-S \
  --num_demos 8000 \
  --demo_times 10 \
  --num_iters 200000 \
  --out_logits 1 \
  --step 4 \
  --exp_name 1107-22-tryseven-S-no_global-step2-no_perturb \
  --max_load 2000 \
  --batch 20 \
  --unet 1 \
  --without_global \
  --learning_rate 1e-4 \
  --model critic \
  --image_size 160 \
  --load_aff_dir checkpoints/rope-configuration-Aff_Critic-7001-1106-03-S-2:1-no_global-online-aff-step-2-0.06-step-1/attention-online-ckpt-7000.h5 \
  --no_perturb \
