CUDA_VISIBLE_DEVICES=5 python ./softgym/train.py \
  --env_name RopeConfiguration \
  --task rope-configuration \
  --agent aff_critic \
  --suffix tryseven-step3-S \
  --num_demos 8000 \
  --demo_times 10 \
  --num_iters 100000 \
  --out_logits 1 \
  --step 3 \
  --exp_name 1110-03-tryseven-S-no-global-step3-no_perturb \
  --max_load 5000 \
  --batch 20 \
  --unet 1 \
  --without_global \
  --learning_rate 1e-4 \
  --model critic \
  --image_size 160 \
  --load_aff_dir checkpoints/rope-configuration-Aff_Critic-8000-1109-06-tryseven-no-global-aff-step2-step-1/attention-ckpt-300000.h5 \
  --no_perturb \
